# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sde', '0019_auto_20171231_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jumps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('jumps', models.IntegerField(default=0)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.System')),
            ],
        ),
    ]
