# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180119_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JumpRecords',
            new_name='JumpRecord',
        ),
    ]
