# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180119_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumpsrecord',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumps', to='sde.System'),
        ),
    ]
