# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180124_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
