# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 14:49
from __future__ import unicode_literals
from datetime import timedelta

from django.db import migrations, models, transaction
import django.db.models.deletion


from core.models import Sequence, JumpsRecord


def match_sequences(apps, schema_editor):
    jumps = JumpsRecord.objects.filter(
        sequence__isnull=True
    ).order_by(
        'date',
        'system_id'
    ).all()

    last = None
    for jump in jumps:
        if last == None or jump.date >= last.date + timedelta(seconds=10):
            sequence = Sequence(
                date=jump.date
            )
            sequence.save()
            print(sequence)
        
        jump.sequence = sequence
        jump.save()

        last = jump


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180124_1719'),
    ]

    operations = [
        migrations.RunPython(match_sequences)
    ]
