# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_sequences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumpsrecord',
            name='date',
        ),
    ]
