# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-22 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0019_auto_20171231_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemJump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumps_destination', to='sde.System')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumps_origin', to='sde.System')),
            ],
        ),
    ]
